BaseURL = "https://www.scagnt.org/"
languageCode = "en-us"
title = "Algebra, Geometry, and Number Theory at the University of South Carolina"
theme = "research_group"
relativeURLS = true
googleAnalytics = "G-8S5KWYDY30"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Team"
    url = "/team/"
    weight = 2
  [[menu.nav]]
    name = "Research"
    url = "/research/"
    weight = 3
  [[menu.nav]]
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.nav]]
    name = "Events"
    url = "/events/"
    weight = 5
  [[menu.nav]]
    name = "Courses"
    url = "/courses/"
    weight = 6
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 7

[params]
  author = "SCAGNT"
  description = "Website for the research group Algebra, Geometry, and Number Theory at the University of South Carolina"
  logo = "https://www.scagnt.org/images/logo.png"
  images = ["/images/site-feature-image.jpg"]

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"